### ISSUE TITLE
Audio and video codec in VideoInfoScreen

### ISSUE THREAD

**Issue by Balinus** [ac3d912/kodi.skin.simplicitiy#14]
I noticed that the alignment is wrong for the video and audio codec in the videoinfoscreen. They are vertically aligned when it should be horizontal.

From memory, it's in the file "VideoInfoScreen.xml".

Medium-prority bug in the sense that it's one of the first thing a new user will see when using the skin.

**Comment by ac3d912** [comment]
Yep, Got that one.  Thanks.
